name: Build and Deploy Marp Slides

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Build slides
        run: |
          marp slides.md -o index.html --allow-local-files
          marp slides.md -o slides.pdf --pdf --allow-local-files

      - name: Upload artifact (PDF)
        uses: actions/upload-artifact@v3
        with:
          name: slides-pdf
          path: slides.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
